// Legal text for TeachBek — Terms of Service and Privacy Policy.
// NOTE: These are general-purpose drafts to set basic expectations and reduce
// liability. They are NOT a substitute for advice from a qualified lawyer.
// Before processing real payments at scale, have a lawyer review these.

export default function Legal({ onClose }) {
  const today = new Date().toLocaleDateString("en-GB", { year: "numeric", month: "long", day: "numeric" });

  return (
    <div onClick={onClose} style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.7)", backdropFilter: "blur(4px)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 200, padding: 20 }}>
      <div onClick={(e) => e.stopPropagation()} style={{ width: "100%", maxWidth: 640, maxHeight: "85vh", overflowY: "auto", background: "#efe0c2", border: "1px solid rgba(120,85,45,0.1)", borderRadius: 20, padding: "32px 32px 40px", position: "relative", fontFamily: "'DM Sans', sans-serif" }}>
        <button onClick={onClose} style={{ position: "sticky", top: 0, float: "right", background: "#efe0c2", border: "none", color: "#8a7256", fontSize: 26, cursor: "pointer", lineHeight: 1 }}>×</button>

        <h1 style={{ color: "#43301d", fontSize: 24, fontWeight: 700, marginBottom: 4 }}>Terms & Privacy</h1>
        <p style={{ color: "#ad9678", fontSize: 13, marginBottom: 24, fontFamily: "'Space Mono', monospace" }}>Last updated: {today}</p>

        <div style={{ color: "#5a4530", fontSize: 14.5, lineHeight: 1.7 }}>
          <h2 style={S.h2}>1. About TeachBek</h2>
          <p style={S.p}>TeachBek is an online tool that helps you practise English through conversation with an AI assistant. By creating an account or using TeachBek, you agree to these Terms. If you do not agree, please do not use the service.</p>

          <h2 style={S.h2}>2. AI Can Make Mistakes</h2>
          <p style={S.p}>TeachBek's responses, corrections, explanations, and any practice scores (including IELTS or TOEFL-style estimates) are generated by artificial intelligence. They may be incomplete, inaccurate, or wrong. TeachBek is a practice aid only and is <strong style={S.strong}>not a substitute for a qualified human teacher, tutor, or official examination</strong>. Any score or level shown is an approximate estimate and has no official standing. Always verify important information independently. You use TeachBek's output at your own discretion and risk.</p>

          <h2 style={S.h2}>3. No Guarantees</h2>
          <p style={S.p}>The service is provided "as is" and "as available", without warranties of any kind, whether express or implied. We do not guarantee that the service will be uninterrupted, error-free, secure, or that it will improve your English or exam results. To the fullest extent permitted by law, TeachBek and its owner are not liable for any loss or damage arising from your use of, or reliance on, the service or its output.</p>

          <h2 style={S.h2}>4. Acceptable Use</h2>
          <p style={S.p}>You agree to use TeachBek lawfully and not to misuse it, including by attempting to break, overload, or reverse-engineer the service, or by using it to create harmful, illegal, or abusive content. We may suspend or close accounts that violate these Terms.</p>

          <h2 style={S.h2}>5. Accounts</h2>
          <p style={S.p}>You are responsible for keeping your login details secure and for activity under your account. You must provide a valid email address and be old enough to use the service under the laws of your country.</p>

          <h2 style={S.h2}>6. Free Use and Premium</h2>
          <p style={S.p}>TeachBek offers a limited number of free messages per day. A paid Premium plan may offer additional usage and features. Prices and limits may change. Where payments are processed, they are handled by third-party payment providers; we do not store your full card or payment details.</p>

          <h2 style={S.h2}>7. Privacy Policy</h2>
          <p style={S.p}>We collect only what we need to run the service: your email address (for login) and the messages you send, so your conversations can be saved and shown back to you. Your messages are sent to our AI provider to generate replies. We do not sell your personal data. We use trusted third-party services (for hosting, database, authentication, and AI) that process data on our behalf.</p>
          <p style={S.p}>Your conversations are private to your account. You can delete individual chats at any time. If you want your account and data fully removed, contact us and we will delete them.</p>

          <h2 style={S.h2}>8. Changes</h2>
          <p style={S.p}>We may update these Terms from time to time. Continued use after changes means you accept the updated Terms.</p>

          <h2 style={S.h2}>9. Contact</h2>
          <p style={S.p}>For any questions about these Terms or your data, please contact the TeachBek team through the email associated with the service.</p>

          <p style={{ ...S.p, color: "#9a8264", fontSize: 13, marginTop: 28, borderTop: "1px solid rgba(120,85,45,0.08)", paddingTop: 16 }}>
            This document is a plain-language summary intended to set clear expectations. It is not legal advice. For full legal protection, especially once paid subscriptions are active, these terms should be reviewed by a qualified lawyer in your jurisdiction.
          </p>
        </div>
      </div>
    </div>
  );
}

const S = {
  h2: { color: "#43301d", fontSize: 16, fontWeight: 600, marginTop: 22, marginBottom: 6 },
  p: { marginBottom: 10 },
  strong: { color: "#43301d" },
};
