// Public, no-login pages required for Paddle verification:
// /pricing, /terms, /privacy, /refund
// NOTE: These are plain-language drafts. Have a lawyer review before scaling.

const wrap = {
  minHeight: "100vh", background: "#f7eedd", color: "#5a4530",
  fontFamily: "'DM Sans', sans-serif", padding: "40px 20px",
};
const inner = { maxWidth: 760, margin: "0 auto" };
const h1 = { color: "#43301d", fontSize: 30, fontWeight: 700, marginBottom: 6, letterSpacing: -0.5 };
const h2 = { color: "#43301d", fontSize: 18, fontWeight: 600, marginTop: 26, marginBottom: 8 };
const p = { fontSize: 15, lineHeight: 1.75, marginBottom: 10 };
const small = { color: "#ad9678", fontSize: 13, fontFamily: "'Space Mono', monospace" };
const strong = { color: "#43301d" };

function Shell({ title, updated, children }) {
  return (
    <div style={wrap}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600;700&family=Space+Mono:wght@400;700&display=swap');`}</style>
      <div style={inner}>
        <a href="/" style={{ color: "#a96a32", textDecoration: "none", fontSize: 14, fontFamily: "'Space Mono', monospace" }}>← Back to TeachBek</a>
        <div style={{ display: "flex", alignItems: "center", gap: 12, marginTop: 24, marginBottom: 4 }}>
          <div style={{ width: 40, height: 40, borderRadius: 11, background: "linear-gradient(135deg, #a96a32, #d2a25e)", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 800, color: "#fff8ec" }}>T</div>
          <span style={{ color: "#43301d", fontWeight: 700, fontSize: 18 }}>TeachBek</span>
        </div>
        <h1 style={h1}>{title}</h1>
        {updated && <p style={small}>Last updated: {updated}</p>}
        <div style={{ marginTop: 20 }}>{children}</div>
        <p style={{ ...small, marginTop: 40, borderTop: "1px solid rgba(120,85,45,0.08)", paddingTop: 16 }}>
          Questions? Contact us on Telegram @sean_fan.
        </p>
      </div>
    </div>
  );
}

function Pricing() {
  return (
    <Shell title="Pricing">
      <p style={p}>TeachBek is an AI-powered English learning assistant. You can practise English through conversation, get your mistakes corrected, track your progress, and prepare for exams.</p>

      <h2 style={h2}>Free plan — 0₸</h2>
      <p style={p}>
        Includes: up to <strong style={strong}>20 messages per day</strong> with the AI tutor, automatic mistake corrections, level estimate (A1–C2), daily streaks, progress tracking, instant word translation, and AI-suggested conversation topics.
      </p>

      <h2 style={h2}>Premium — 2500₸ / month (about $5)</h2>
      <p style={p}>Everything in the Free plan, plus:</p>
      <p style={p}>
        • <strong style={strong}>Unlimited messages</strong> every day<br/>
        • <strong style={strong}>IELTS &amp; TOEFL practice</strong> — an AI examiner with band-score feedback<br/>
        • <strong style={strong}>Essay &amp; writing check</strong> — paste any text and get detailed corrections<br/>
        • <strong style={strong}>Personal study plan</strong> built from your level and your most common mistakes<br/>
        • <strong style={strong}>Priority support</strong>
      </p>
      <p style={p}>Premium is a monthly subscription billed at 2500₸ (approximately $5 USD, charged in the equivalent local amount). You can cancel at any time; see our Refund Policy for details.</p>
    </Shell>
  );
}

function Terms() {
  return (
    <Shell title="Terms of Service" updated="June 2026">
      <h2 style={h2}>1. About TeachBek</h2>
      <p style={p}>TeachBek ("we", "us") is an online tool that helps you practise English through conversation with an AI assistant. By creating an account or using TeachBek, you agree to these Terms. If you do not agree, please do not use the service.</p>

      <h2 style={h2}>2. AI can make mistakes</h2>
      <p style={p}>TeachBek's responses, corrections, level estimates, and any practice scores (including IELTS or TOEFL-style estimates) are generated by artificial intelligence and may be incomplete or incorrect. TeachBek is a practice aid only and is <strong style={strong}>not a substitute for a qualified human teacher, tutor, or official examination</strong>. Any score or level shown is an approximate estimate with no official standing.</p>

      <h2 style={h2}>3. No guarantees</h2>
      <p style={p}>The service is provided "as is" and "as available", without warranties of any kind. We do not guarantee it will be uninterrupted, error-free, or that it will improve your English or exam results. To the fullest extent permitted by law, we are not liable for any loss arising from your use of, or reliance on, the service.</p>

      <h2 style={h2}>4. Acceptable use</h2>
      <p style={p}>You agree to use TeachBek lawfully and not to misuse it, including attempting to break, overload, or reverse-engineer it, or using it to create harmful or illegal content. We may suspend accounts that violate these Terms.</p>

      <h2 style={h2}>5. Accounts</h2>
      <p style={p}>You are responsible for keeping your login secure and for activity under your account. You must provide a valid email and be old enough to use the service under the laws of your country.</p>

      <h2 style={h2}>6. Payments</h2>
      <p style={p}>Premium is a paid monthly subscription. Payments are processed by third-party payment providers; we do not store your full card details. Prices and features may change with notice.</p>

      <h2 style={h2}>7. Changes</h2>
      <p style={p}>We may update these Terms from time to time. Continued use after changes means you accept the updated Terms.</p>
    </Shell>
  );
}

function Privacy() {
  return (
    <Shell title="Privacy Policy" updated="June 2026">
      <h2 style={h2}>What we collect</h2>
      <p style={p}>We collect only what we need to run the service: your <strong style={strong}>email address</strong> (for login) and the <strong style={strong}>messages you send</strong>, so your conversations can be saved and shown back to you.</p>

      <h2 style={h2}>How we use it</h2>
      <p style={p}>Your messages are sent to our AI provider to generate replies and corrections. We use your data only to provide and improve the service. We do <strong style={strong}>not</strong> sell your personal data.</p>

      <h2 style={h2}>Third parties</h2>
      <p style={p}>We use trusted providers that process data on our behalf: hosting, database and authentication, the AI model provider, and our payment provider. Each processes data only to deliver their part of the service.</p>

      <h2 style={h2}>Your data, your control</h2>
      <p style={p}>Your conversations are private to your account. You can delete individual chats at any time. To have your account and all data permanently removed, contact us and we will delete them.</p>

      <h2 style={h2}>Security</h2>
      <p style={p}>We take reasonable measures to protect your data, but no online service can be guaranteed 100% secure.</p>
    </Shell>
  );
}

function Refund() {
  return (
    <Shell title="Refund Policy" updated="June 2026">
      <h2 style={h2}>Subscriptions</h2>
      <p style={p}>TeachBek Premium is a monthly subscription. You can cancel at any time, and your Premium access will remain active until the end of the period you have already paid for.</p>

      <h2 style={h2}>Refunds</h2>
      <p style={p}>If you are not satisfied, you may request a refund within <strong style={strong}>14 days</strong> of your payment by contacting us, provided the request is reasonable and the service was not substantially used or abused. Approved refunds are issued to your original payment method.</p>

      <h2 style={h2}>Partial periods</h2>
      <p style={p}>We do not provide partial refunds for unused days of an active subscription period after the 14-day window, but you keep access until that period ends.</p>

      <h2 style={h2}>How to request</h2>
      <p style={p}>To cancel or request a refund, contact us on Telegram <strong style={strong}>@sean_fan</strong> with the email used for your account. We aim to respond within a few days.</p>
    </Shell>
  );
}

export default function PublicPage({ page }) {
  if (page === "pricing") return <Pricing />;
  if (page === "terms") return <Terms />;
  if (page === "privacy") return <Privacy />;
  if (page === "refund") return <Refund />;
  return null;
}
